feature(multi-site-demo): teraform apply updated to use new patterns

diff --git a/multi-site/tasks/terraform-apply.yaml b/multi-site/tasks/terraform-apply.yaml
--- a/multi-site/tasks/terraform-apply.yaml
+++ b/multi-site/tasks/terraform-apply.yaml
@@ -1,61 +1,185 @@
 ---
-Description: "A task run Terraform Templates"
 Name: "terraform-apply"
+Description: "A task run Terraform Templates"
+Documentation: |
+  Runs one or more Terraform Plan templates as defined by the
+  ``terraform/plan-templates`` variable in the stage calling the task.
+
+  Requires an ``terraform`` context.
+
+  The ``terraform apply`` is only called once.  All plans in the list 
+  are generated first.  If sequential operations beyond the plan are needed, use
+  multiple calls to this task.
+
+  Information can be chained together by having the plan output saved
+  on the machine as ``Param.terraform/output``.  Only parts of the Machine are
+  automatically passed into the plan; however, the plans can use the .Param
+  and .ParamExists template renders to pull anything needed.
+
+  Terraform State is stored as a param on the Machine after execution.
+
+  Note: having SSH keys requires using the sshkey generator task.
 RequiredParams:
-  - "terraform/state-username"
-  - "terraform/state-password"
-OptionalParams:
+  - "terraform/plan-templates"
   - "terraform/plan-action"
+OptionalParams:
+  - rsa/key-user
+  - rsa/key-public
 Templates:
-  - Contents: |-
-      {{template "terraform-backend.tf.tmpl" .}}
-
-      {{template "terraform-linode.tf.tmpl" .}}
-
-      {{ $prefix := .Param "demo/cluster-prefix" -}}
-      {{ $region := .Param "linode/region" -}}
-      resource "linode_instance" "drp_endpoint" {
-        image     = "{{ .Param "linode/instance-image" }}"
-        label     = "{{ .Machine.Name }}"
-        region    = "{{ $region }}"
-        type      = "{{ .Param "linode/instance-type" }}"
-        root_pass = "{{ .Param "linode/root-password" }}"
-        tags      = [ "cluster-{{ $prefix }}" ]
-
-        stackscript_id = {{ .Param "linode/stackscript_id" }}
-        stackscript_data = {
-          "drp_ip" = "{{ .ProvisionerAddress }}"
-          "drp_port" = "8091"
-          "open_ports" = "22 8092 8091 2379 2380 6443 10250"
-          "rs_uuid" = "{{ .Machine.Uuid }}"
-        }
+  - Name: "DRP Variables"
+    Path: "tf.vars"
+    Contents: |-
+      # automatically added by DRP terraform-apply
+      variable "drp_url" {
+        type      = string
+        default   = "{{ .ProvisionerURL }}"
       }
-
-      resource "linode_instance" "drp_nodes" {
-        count     = "{{ .Param "demo/cluster-count" }}"
-        image     = "{{ .Param "linode/instance-image" }}"
-        label     = "{{ .Machine.Name }}-node-${count.index + 10}"
-        region    = "{{ $region }}"
-        type      = "{{ .Param "linode/instance-type" }}"
-        root_pass = "{{ .Param "linode/root-password" }}"
-        tags      = [ "cluster-{{ $prefix }}" ]
-
-        stackscript_id = {{ .Param "linode/stackscript_id" }}
-        stackscript_data = {
-          "drp_ip" = linode_instance.drp_endpoint.ip_address
-          "drp_port" = "8091"
-          "open_ports" = "22 8092 8091 2379 2380 6443 10250"
-        }
+      {{ if .ParamExists "rsa/key-public" }}variable "ssh_key" {
+        type      = string
+        default   = "{{ .Param "rsa/key-public" }}"
+      }{{ end }}
+      {{ if .ParamExists "rsa/key-user" }}variable "ssh_user" {
+        type      = string
+        default   = "{{ .Param "rsa/key-user" }}"
+      }{{ end }}
+      variable "machine_uuid" {
+        type      = string
+        default   = "{{ .Machine.Uuid }}"
       }
-
-      output "machine_ip" {
-        value       = linode_instance.drp_endpoint.ip_address
-        description = "The IP of DRP"
+      variable "machine_name" {
+        type      = string
+        default   = "{{ .Machine.Name }}"
       }
-    Name: "digitalrebar.tf"
-    Path: "digitalrebar.tf"
-  - ID: "terraform-apply.sh.tmpl"
-    Name: "Terraform Init and Apply Plan"
+      variable "machine_addr" {
+        type      = string
+        default   = "{{ .Machine.Address }}"
+      }
+      # end auto block
+
+  - Name: "terraform-apply.sh"
+    Contents: |-
+      #!/bin/bash
+      # RackN Copyright 2020
+
+      set -e
+
+      {{template "setup.tmpl" .}}
+
+      {{ if $.ParamExists "rs-debug-enable" }}
+      showplan={{ if eq ($.Param "rs-debug-enable") true }}true{{else}}false{{end}}
+      {{ end }}
+      tfstate="set"
+      success=true
+      echo "Retrieving terraform.tfstate file from machine"
+      {{ if .ParamExists "terraform/tfstate" }}
+      tee terraform.tfstate > /dev/null << EOF
+      {{ .ParamAsJSON "terraform/tfstate" }}
+      EOF
+      if [[ $showplan == true ]]; then
+        echo "DEBUG: terraform.tfstate"
+        cat terraform.tfstate | jq .
+      fi
+      {{ else }}
+      tfstate="add"
+      if [[ -e terraform.tfstate ]] ; then
+        echo "WARNING: tfstate file exists: uploading now, keeping in place"
+        drpcli machines $tfstate $RS_UUID param terraform/tfstate to - < terraform.tfstate
+      else
+        echo "no terraform/tfstate exists"
+      fi
+      {{ end }}
+      
+      {{ $machine := .Machine.Name -}}
+      {{ $action := .Param "terraform/plan-action" -}}
+      {{ range $index, $plan := (.Param "terraform/plan-templates") -}}
+      {{ $plan := printf "%s" $plan -}}
+
+      ## Build Plan
+      echo "============== Build Plan {{$index}}: {{$plan}} =============="
+      echo "Building from Template {{ $plan }}"
+      tee {{$plan}}.tf >/dev/null << EOF
+      $(cat tf.vars)
+      # >> start of {{$plan}}
+      {{$.CallTemplate $plan $}}
+      # << end of {{$plan}}
+      EOF
+
+      if [[ $showplan == true ]]; then
+        echo "DEBUG: {{$plan}}.tf"
+        cat {{$plan}}.tf
+      fi
+
+      echo "^^^^^ end of {{$plan}} loop ^^^^^ "
+      {{ end }}
+
+      echo "=== INIT $(terraform version) ===="
+
+      terraform init -no-color
+
+      if [[ $showplan == true ]]; then
+        echo "=== PLAN (DEBUG) TERRAFORM ===="
+        terraform plan -no-color
+      fi
+
+      echo "=== RUN {{ $action }} TERRAFORM ===="
+
+      if terraform {{ $action }} -no-color -auto-approve ; then
+
+        echo "terraform {{ $action }} succeeded!"
+
+        {{ if eq "apply" $action }}
+
+        out=$(terraform output --json | jq .)
+        if [[ $showplan == true ]]; then
+          echo "DEBUG: output"
+          echo "capturing terraform output: $out"
+        fi
+        ip=$(jq -r '.machine_ip.value' <<< ${out})
+        if [[ $ip =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
+          echo "Detected IP from TF, Updateing Machine IP to $ip"
+          drpcli machines update $RS_UUID "{\"Address\":\"$ip\"}" | jq .Address
+        else
+          echo "No IP address (machine_ip.value) detected in terraform output"
+        fi
+
+        # capture all the output vars in the parms
+        echo "uploading other keys from terraform output"
+        for key in $(jq -r 'keys[]' <<< ${out}); do
+          echo "  adding $key to machine"
+          drpcli machines set $RS_UUID param "terraform-var/$key" to "$(jq -r ".$key.value" <<< ${out})"
+        done
+
+        {{ else }}
+            {{ if .ParamExists "terraform-var/machine_ip" }}          
+              echo "Clear IP and terraform-var/machine_ip when performing destroy with IP"
+              drpcli machines update $RS_UUID "{\"Address\":\"\"}" | jq .Address
+               drpcli machines remove $RS_UUID param terraform-var/machine_ip
+            {{ else }}
+              echo "Does not set IP, do not clear IP"
+            {{ end }}
+        {{ end }}
+
+      else
+
+        success=false
+        echo "terraform {{ $action }} failed!"
+
+      fi
+
+      if [[ -e terraform.tfstate ]] ; then
+        echo "Saving terraform.tfstate file to machine"
+        drpcli machines $tfstate $RS_UUID param terraform/tfstate to - < terraform.tfstate
+      else
+        echo "no terraform.state file exists - cannot save"
+      fi
+
+      if [[ $success != true ]] ; then
+        echo "Did not succeed - fail"
+        exit 1
+      fi
+
+      echo "done"
+      # end
 Meta:
   icon: "map"
   color: "blue"
